### ISSUE TITLE
冒昧问一下, 是从哪里采集的数据?

### ISSUE THREAD

**Issue by Silas-Zhu** [newIronRemain/city#1]
冒昧问一下, 是从哪里采集的行政区域的数据, 还是自己整理的?
刚好最近也需要这样的数据

**Comment by newIronRemain** [comment]
同事提供的两个xml文档，在citymodule/web/xml/目录下面

**Comment by newIronRemain** [comment]
> 冒昧问一下, 是从哪里采集的行政区域的数据, 还是自己整理的?
> 刚好最近也需要这样的数据

同事提供的两个xml文档，在citymodule/web/xml/目录下面

**Comment by Silas-Zhu** [comment]
谢谢了
